-- ============================================================
-- Quest Forge — Migration 021
-- Expand educational challenges for new subjects.
-- ============================================================

INSERT INTO edu_challenges (title, subject, age_tier, difficulty, xp_reward, challenge_type, content, is_active) VALUES
-- General Knowledge (Senior)
('World Capitals', 'general_knowledge', 'senior', 4, 35, 'quiz', '{"question": "What is the capital city of France?", "type": "multiple_choice", "options": ["London", "Berlin", "Paris", "Rome"], "correct_answer": "Paris", "explanation": "Paris is the capital and largest city of France."}'::jsonb, true),
('Oceanography', 'general_knowledge', 'senior', 3, 30, 'quiz', '{"question": "Which is the largest ocean on Earth?", "type": "multiple_choice", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "correct_answer": "Pacific", "explanation": "The Pacific Ocean covers about one-third of the Earth''s surface."}'::jsonb, true),
('Space Exploration', 'general_knowledge', 'senior', 5, 40, 'quiz', '{"question": "Who was the first person to walk on the moon?", "type": "multiple_choice", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], "correct_answer": "Neil Armstrong", "explanation": "Neil Armstrong stepped onto the lunar surface on July 20, 1969."}'::jsonb, true),
('Human Biology', 'general_knowledge', 'senior', 2, 25, 'quiz', '{"question": "What is the largest organ in the human body?", "type": "multiple_choice", "options": ["Heart", "Liver", "Skin", "Lungs"], "correct_answer": "Skin", "explanation": "The skin protects our internal organs and regulates body temperature."}'::jsonb, true),
('Astronomy Basics', 'general_knowledge', 'senior', 1, 25, 'quiz', '{"question": "Which planet is closest to the Sun?", "type": "multiple_choice", "options": ["Venus", "Mars", "Mercury", "Earth"], "correct_answer": "Mercury", "explanation": "Mercury is the smallest and innermost planet in the Solar System."}'::jsonb, true),
('Anatomy', 'general_knowledge', 'senior', 4, 35, 'quiz', '{"question": "How many bones are in the average adult human body?", "type": "multiple_choice", "options": ["186", "206", "256", "306"], "correct_answer": "206", "explanation": "Humans are born with more bones, but many fuse together as they grow into adults."}'::jsonb, true),
('Art History', 'general_knowledge', 'senior', 3, 30, 'quiz', '{"question": "Who painted the Mona Lisa?", "type": "multiple_choice", "options": ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], "correct_answer": "Leonardo da Vinci", "explanation": "Da Vinci painted this masterpiece during the Italian Renaissance."}'::jsonb, true),
('Chemistry', 'general_knowledge', 'senior', 5, 40, 'quiz', '{"question": "What is the chemical symbol for Gold?", "type": "multiple_choice", "options": ["Ag", "Fe", "Au", "Pb"], "correct_answer": "Au", "explanation": "The symbol Au comes from the Latin word for gold, ''aurum''."}'::jsonb, true),
('Zoology', 'general_knowledge', 'senior', 1, 20, 'quiz', '{"question": "Which is the fastest land animal?", "type": "multiple_choice", "options": ["Lion", "Cheetah", "Leopard", "Antelope"], "correct_answer": "Cheetah", "explanation": "Cheetahs can reach speeds of up to 70 miles per hour."}'::jsonb, true),
('Modern History', 'general_knowledge', 'senior', 5, 45, 'quiz', '{"question": "In what year did World War II end?", "type": "multiple_choice", "options": ["1918", "1939", "1945", "1950"], "correct_answer": "1945", "explanation": "The war ended with the surrender of the Axis powers in 1945."}'::jsonb, true),

-- Life Skills (Senior)
('First Aid', 'life_skills', 'senior', 3, 30, 'quiz', '{"question": "What is the first step in the basic CPR cycle for an adult?", "type": "multiple_choice", "options": ["Check for breathing", "Call for help", "Chest compressions", "Give rescue breaths"], "correct_answer": "Chest compressions", "explanation": "Current guidelines emphasize high-quality chest compressions as the priority."}'::jsonb, true),
('Financial Literacy', 'life_skills', 'senior', 5, 40, 'quiz', '{"question": "Why is a good credit score important?", "type": "multiple_choice", "options": ["It makes you look good", "It helps you get loans with lower interest", "It is required for voting", "It means you have more money"], "correct_answer": "It helps you get loans with lower interest", "explanation": "Lenders use credit scores to determine how likely you are to repay a loan."}'::jsonb, true),
('Budgeting', 'life_skills', 'senior', 4, 35, 'quiz', '{"question": "The 50/30/20 rule of budgeting suggests spending 50% of your income on:", "type": "multiple_choice", "options": ["Savings", "Wants", "Needs", "Entertainment"], "correct_answer": "Needs", "explanation": "Needs include essentials like rent, groceries, and utilities."}'::jsonb, true),
('Home Safety', 'life_skills', 'senior', 2, 25, 'quiz', '{"question": "What is the best way to extinguish a small grease fire in a pan?", "type": "multiple_choice", "options": ["Pour water on it", "Slide a lid over it", "Fan it with a towel", "Blow on it"], "correct_answer": "Slide a lid over it", "explanation": "Covering the pan smothers the fire by removing oxygen. NEVER use water on a grease fire."}'::jsonb, true),
('Civics', 'life_skills', 'senior', 1, 20, 'quiz', '{"question": "What is the minimum legal voting age in the United States?", "type": "multiple_choice", "options": ["16", "18", "21", "25"], "correct_answer": "18", "explanation": "The 26th Amendment lowered the voting age from 21 to 18 in 1971."}'::jsonb, true),
('Kitchen Skills', 'life_skills', 'senior', 3, 30, 'quiz', '{"question": "What is the safe minimum internal temperature for cooked chicken?", "type": "multiple_choice", "options": ["145°F", "155°F", "165°F", "175°F"], "correct_answer": "165°F", "explanation": "Cooking to 165°F ensures that harmful bacteria like Salmonella are killed."}'::jsonb, true),
('Professionalism', 'life_skills', 'senior', 4, 35, 'quiz', '{"question": "What should you usually do within 24 hours after a job interview?", "type": "multiple_choice", "options": ["Call to ask if you got the job", "Send a thank-you note or email", "Post about it on social media", "Wait for them to call you"], "correct_answer": "Send a thank-you note or email", "explanation": "A thank-you note shows appreciation and reinforces your interest in the position."}'::jsonb, true),
('Emotional Intelligence', 'life_skills', 'senior', 2, 25, 'quiz', '{"question": "Which of these is a key part of active listening?", "type": "multiple_choice", "options": ["Thinking about your reply", "Interrupting with questions", "Maintaining eye contact and summarizing", "Looking at your phone"], "correct_answer": "Maintaining eye contact and summarizing", "explanation": "Active listening involves fully concentrating on and understanding the speaker."}'::jsonb, true),
('Maintenance', 'life_skills', 'senior', 1, 20, 'quiz', '{"question": "How often should you test the batteries in your home smoke detectors?", "type": "multiple_choice", "options": ["Once a week", "Once a month", "Once a year", "Never"], "correct_answer": "Once a month", "explanation": "Monthly testing ensures that the detectors will work in case of a fire."}'::jsonb, true),
('Health: Burns', 'life_skills', 'senior', 2, 25, 'quiz', '{"question": "What is the first thing you should do for a minor thermal burn?", "type": "multiple_choice", "options": ["Apply butter", "Use ice directly", "Run cool water over it", "Pop any blisters"], "correct_answer": "Run cool water over it", "explanation": "Cool running water helps stop the burning process and soothe the skin. Never use ice or butter."}'::jsonb, true)
ON CONFLICT (title, subject, age_tier) DO NOTHING;
